# Usa la imagen de Node.js adecuada
FROM node:22.7.0-alpine AS build

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos necesarios para la construcción
COPY package*.json .

# Instala las dependencias
RUN npm ci --only=production

# Copia el resto del proyecto dentro del contenedor
COPY . .

RUN npm run build

# Expone el puerto donde correrá la aplicación
EXPOSE 4321

# Run de la aplicacion
CMD ["npm", "run", "prod"]
